### ISSUE TITLE
getimage() *sometimes* hangs after restarting camera

### ISSUE THREAD

**Issue by ianshmean** [samuelpowell/Spinnaker.jl#36]
I'm trying to implement pause functionality. Is `stop!(cam)` doing more than just stopping? If so, perhaps there should be a `pause!(cam)`
```julia
julia> using Spinnaker

julia> cam = CameraList()[0]
Point Grey Research Grasshopper3 GS3-U3-32S4M (xxxxxxxx)

julia> start!(cam)
Point Grey Research Grasshopper3 GS3-U3-32S4M (xxxxxxxx)

julia> getimage(cam)
Spinnaker Image, (2048, 1536), 8bpp, PixelFormat_Mono8(0)

julia> stop!(cam)
Point Grey Research Grasshopper3 GS3-U3-32S4M (xxxxxxxx)

julia> start!(cam)
Point Grey Research Grasshopper3 GS3-U3-32S4M (xxxxxxxx)

julia> getimage(cam)
<hangs>
```

**Comment by ianshmean** [comment]
This behaviour seems to be chaotic when manually testing it like above, but happens reliably in the SpinnakerGUI system after restarting after pause, with a terminal hang on getimage()

**Comment by samuelpowell** [comment]
It just calls a single Spinnaker function, so this is unexpected. If you can find any alternatives in Spinnaker let me know!

**Comment by samuelpowell** [comment]
Reported as issue using Spinnaker through VM, can we close this @ianshmean?

**Comment by ianshmean** [comment]
Yeah. USB over VM just too unpredictable to be handled reliably
