### ISSUE TITLE
AcquisitionFrameRateEnabled != AcquisitionFrameRateEnable

### ISSUE THREAD

**Issue by ianshmean** [samuelpowell/Spinnaker.jl#48]
@samuelpowell Is your camera node `AcquisitionFrameRateEnable`? If so, we have another divergent node name. Mine's `AcquisitionFrameRateEnabled`

**Comment by samuelpowell** [comment]
I believe it lacks the ‘d’, see https://github.com/ianshmean/SpinnakerGUI.jl/issues/4. Feel free to add it to the names dictionary or I shall do so later!

**Comment by samuelpowell** [comment]
@ianshmean this was fixed in #49?

**Comment by samuelpowell** [comment]
Assume fixed in #49 please reopen if not.
