### ISSUE TITLE
add method to getimage!() most recent image during continuous mode?

### ISSUE THREAD

**Issue by ianshmean** [samuelpowell/Spinnaker.jl#6]
`getimage!()` during continuous mode seems to grab the next image in the buffer, rather than the most recently captured. Meaning that if the grab loop is slower than framerate, a lag builds between the image being grabbed and captured.

I'm wondering whether a way to getimage!() on the most recently captured image during continuous mode would be helpful... Does spinnaker provide that functionality?

**Comment by samuelpowell** [comment]
Yes this should be possible, see https://www.ptgrey.com/tan/11174, I assume you want the "Newest Only" mode?

**Comment by samuelpowell** [comment]
I have implemented the desired functionality in #8, could you test that this meets your requirements and is bug free?

**Comment by samuelpowell** [comment]
@ianshmean tested locally and working well, please reopen issue if you have any problems.
